### ISSUE TITLE
Is libasan.so neccessary?

### ISSUE THREAD

**Issue by nickhuangxinyu** [misc0110/colorful-printf#1]
Hi, great repo!

but when i make. i met:

```
gcc test.c colorprint.c -fsanitize=address -g -Wall -Wextra -o test
/usr/bin/ld: cannot find /usr/lib64/libasan.so.5.0.0
collect2: error: ld returned 1 exit status
make: *** [Makefile:2: all] Error 1

```

is libasan.so neccessary?

I use the simple command:
`gcc test.c colorprint.c`

this works fine.

so what is the function of libasan? can you let me know that?

**Comment by misc0110** [comment]
libasan ([Address Sanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer)) is only for testing, it is not required for any of the functionality (see https://github.com/misc0110/colorful-printf#usage).
